# Generated by Django 4.1 on 2022-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=50)),
                ('food_title', models.CharField(max_length=50)),
                ('food_price', models.IntegerField(default=0)),
                ('food_desc', models.TextField(max_length=100)),
                ('food_img', models.ImageField(default='', upload_to='food/images')),
            ],
        ),
    ]
