# Generated by Django 4.1 on 2022-08-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfood',
            name='food_img',
            field=models.ImageField(height_field=600, upload_to='food/images', width_field=600),
        ),
    ]
