# Generated by Django 4.1 on 2022-08-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_alter_myfood_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfood',
            name='food_img',
            field=models.ImageField(default='', upload_to='food/images'),
        ),
    ]
