# Generated by Django 4.1 on 2022-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_alter_myfood_food_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_people', models.IntegerField(default=0)),
            ],
        ),
    ]
