# Generated by Django 4.1 on 2022-08-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_bootable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooTable',
            new_name='BookTable',
        ),
    ]
