# Generated by Django 4.1 on 2022-08-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0005_rename_bootable_booktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='mdg',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
