# Generated by Django 4.1 on 2022-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfood',
            name='id',
        ),
        migrations.AddField(
            model_name='myfood',
            name='food_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
