# Generated by Django 4.1 on 2022-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0009_remove_myfood_id_myfood_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfood',
            name='food_price',
            field=models.FloatField(default=0),
        ),
    ]
