# Generated by Django 4.1 on 2022-08-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_alter_myfood_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.TextField(max_length=100)),
                ('no_ofDish', models.IntegerField(default=0)),
                ('msg', models.TextField(max_length=100)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.myfood')),
            ],
        ),
    ]
