# Generated by Django 4.1 on 2022-08-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_id',
        ),
    ]
