# Generated by Django 4.1 on 2022-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0012_remove_order_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no_ofDish',
            field=models.IntegerField(),
        ),
    ]
