# Generated by Django 4.1 on 2022-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0014_alter_order_no_ofdish_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_desc',
            field=models.TextField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='food_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='food_title',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='food_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
